language: python

python:
  - 3.6

services:
  - docker

before_install:
  - docker build -t flashcards-123/web .
  - docker run -p 5000:5000 flashcards-123/web -c "cd /opt/webapp; python manage.py test"
  - docker ps -a

script:
  - cd /opt/webapp; python manage.py test

