# Generated by Django 2.1.5 on 2019-01-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_primary', models.CharField(max_length=512)),
                ('name_secondary', models.CharField(max_length=512)),
                ('description_primary', models.TextField(max_length=1024)),
                ('description_secondary', models.TextField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(max_length=1024)),
                ('ar', models.CharField(max_length=1024)),
            ],
        ),
    ]
