# Generated by Django 2.1.5 on 2019-01-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_word_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description_ar',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
